### ISSUE TITLE
ValueError: zero length field name in format

### ISSUE THREAD

**Issue by systems1** [daniellawrence/graphitesend#47] opened 2016-03-16 18:14 UTC
I am getting below valueerror anyone else has similar error 

Traceback (most recent call last):
  File "/usr/bin/graphitesend", line 9, in <module>
    load_entry_point('graphitesend==0.6.0', 'console_scripts', 'graphitesend')()
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 609, in cli
    graphitesend_instance.send(metric, value)
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 346, in send
    return self._dispatch_send(message)
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 259, in _dispatch_send
    len(message), message)
ValueError: zero length field name in format

**Comment by daniellawrence** [comment] 2016-03-17 01:34
Hey @systems1,

 What are you executing in order to get that error?

**Comment by systems1** [comment] 2016-03-17 15:39
python -V
Python 2.6.6

>>> import graphitesend
>>> g = graphitesend.init(prefix='test2.server2')
>>> g.send('cpu_use', 74)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 346                                          , in send
    return self._dispatch_send(message)
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 259                                          , in _dispatch_send
    len(message), message)
ValueError: zero length field name in format

**Comment by systems1** [comment] 2016-03-17 15:41
getting same error via cli on linux server 
>graphitesend test2.server2.cpu_busy 66

Traceback (most recent call last):
  File "/usr/bin/graphitesend", line 9, in <module>
    load_entry_point('graphitesend==0.6.0', 'console_scripts', 'graphitesend')()
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 609, in cli
    graphitesend_instance.send(metric, value)
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 346, in send
    return self._dispatch_send(message)
  File "/usr/lib/python2.6/site-packages/graphitesend/graphitesend.py", line 259, in _dispatch_send
    len(message), message)
ValueError: zero length field name in format

**Comment by systems1** [comment] 2016-03-21 13:39
Installed python 3.x on windows to test if that works

D:\python\Scripts> graphitesend-script.py test2.server2.metric2 22
Traceback (most recent call last):
  File "D:\python\Scripts\graphitesend-script.py", line 9, in <module>
    load_entry_point('graphitesend==0.6.0', 'console_scripts', 'graphitesend')()

  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 608, in
cli
    graphitesend_instance = init()
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 535, in
init
    _module_instance = GraphiteClient(*args, **kwargs)
  File "D:\python\lib\site-packages\graphitesend\graphitesend.py", line 131, in
__init__
    tmp_sname = '%s.' % os.uname()[1]
AttributeError: 'module' object has no attribute 'uname'

**Comment by daniellawrence** [comment] 2016-03-22 06:24
**AttributeError: 'module' object has no attribute 'uname'**

Well, I know I have never tested this on windows. 
So that would be the cause of the 2nd error, I guess finding a better way to the the hostname would be a good idea.

The below should work, however I need to verify that its going to have the same results as `os.uname()[1]`

```
from socket import gethostname
print gethostname()
```
I have raised https://github.com/daniellawrence/graphitesend/issues/50 to track this issue.

**python 2.6 errors**
I suspect we are hitting an error due to ye old python2.6, I'll fire up a centos 6 box and see if I can replicate the issue.

**Comment by daniellawrence** [comment] 2016-03-22 06:58
The error is the formatting requirements in python2.6, should be an easy fix.

**Comment by daniellawrence** [comment] 2016-03-23 01:44
This has been fixed with 0.7.0 release, windows support has been moved to #50

**Closed by daniellawrence** 2016-03-23 01:44 UTC
Labels: bug, question
